language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "FqZP6Pk9aGa1EoFjmEyN/OOFU/esPRn1SkLXxBwSzXB8s14Ghv33Q37Vy77Vf+0Nq+kurttLaSe1UNF/s9CS+Wfw8J7sp7PwpAAl4ugmEOMB4PZTjW/naZ7xGSXME6vooDpT+AYIbeiD2EawImU1zi7LYh/5i/H2f3DaeV1XRCOaq5TWBj5bCkbYj861wD6QxMRzChN6CQo1Y9DXoU4MatDmL4uTiuBG5icJs9p/o15kF0lwcSUdK9+u2wHE5Ld7TOA0rH24Nf2tuNeTFFn0bv/WXLgx9Nz/Opi0yADxJGG+8xUGHvyD8yS63V1G7PHrXRz7mxB/4mPze47bq3JIAnXS9qQhb9SmKMIzfOhGNdGCtksPQj/d+o9e2PYJd95BWrH4HeZMuNCaugaNoh+CFpN+0mFsygvAKyDIchBVw4OyfgQSj1e4Vy2zumX/vcqGEbbXbOaOMoccm/sw1VUKbyEv1EzxEnElLAUCcxGybmw/vC7FZCxxdwFq+hgZV9dscVm63HVhxDml5qxwLqA51e89mcgFDFkvMsyaIkYvDAPc9WLhvcABMTsmnp3x3ltI7VGD71/UCBFpVNg7pWFvoH3G5DTgQrXmMdmJVKbLZjjLpm9v1Xtk3cierHhNj3myShTzR2hBhacFazxLpr8bGk9NTbLQAbkuDRu1cuqSsh4="
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: "EZZzVvlyZuMJvge/ibkvL98UQxZxg7sCzWEVlBYc4GF4e1Xh63fiDzNn3B4Egwkamx3OC9Nm+HUQ9OcMNrQy4fqhteEstZid+YiF1FnvwnuPQkqCk3N6Tg/AxVH1OtWN9mgwXp3MM5t2q9Mv8g0HF6VN2R/rps4V/jBR2cu+HKjBVlLzG3y8VM8Oc0g/jTXSMhPJcCe9+56LgD/xx53AIxfJ5rTi4GfRhL3VwnbxRfH5FOxOE0054EOatwkbPb8JQd4I1oG6piwurCb2Z844F2r/ChG66+LoGKY3F1n+e2W1tttgIKZuFCikfWMP2KrPF3UckL+mMjn/ZucTjSHsvD2yLnXCVI3bhdTKMEZj7F6H6z1ffhfOa2H/oexSzmsL0YWYTitpJNV1SCeXrpWQgXov0p9BcFgdEWya5bIXBmut6nOEzOaMbdC1cKSDwF0SNr2DnTrO7TeeE+PFyrcKMt4ZgVtDn2W4NiWS2uWmGnL1/Y9enOKHY3V6Qa9EJ6u4JOTCoSV7YViq1WDqmfIlC10gO+c4Avu6Zq2ZtTGtReUIGMjKBIkkEO1Ac6ivkjVie7M4tw+nw93kvQNRJST6osTguIPYAu75oEdcyiOPMl4Z/M4oQU9+DNmv2av5aqwMwjOu5rthpOjUOKoK6vEemmQ3JCGzIa2j/4WrsTAMYxQ="
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: "aP12cT5zKsufqPHad83AptcRI+bbkooAqIGBIDxus0LyIDmV4bdpkkDcwbLO6V9/AgeIyE00Hf+Cw60QkoQFwPhY5nfS9fotRPceSVo2R5f5OBZHiZOx10Zk5IC5i9BA1vuV985a7SbVdSoxveAxg+EmKJ2rJP101EbXbBNYv0E4sXahXX468PnFbFyji15CAhyD56FY1gKX/GXnZnLd9/K0C8kMbhYtEcRHkcD19FfMPqsdphk9l5DHVwkf4FSTifMzKJtf7ySxMKUTIuA3XpEFH3pVqCtG4IKSALr83c4vaAKdc43hI6AZ0iyp6ckQojMjtmCuHuz71g37+kgO1qWI1CFV5mcNGyWygaT6ZKEm0VufvlmzXcEnAzejzSyVlG2o+iJXy69k8HhHadxGUHePKg07DSwPeQ88c0sSx4xOHZVcZ8dReFX+nor1lgV/EuZTQzOCIKxEsjMGsLOZnlUpnrBgG4pk3087v/D5B51G1eS+h8WAh2zo0HokZQbzJGDtwKD4M48XlZMbDS/fzbhZ9XKLCYXCSVxCRaGtbF9hRLk83mE0kzGsm8//GmJIPlXa7/txbM1G6yg/Vt84wEXs4sInDURBv75Cl2v713G7nxRO6PncpxhPZ6v8egKgaOec75JKI06uZPKfphHpPKcy0p/M/jTvTyc2TiA30kU="
    - # ^^ GPG_KEY_NAME
    - secure: "DtUEyDREbcRwGkZLDzZKPQQLwHgqsBCYQK1/BtARYN2j1dsyYEzuA8JQFxr5sawnWM4zd0uhUdvSWt1grq6Db+qQ+HTQuUU2HsME2edG9NYLYSbAypOvATEryvHoLT7Mbl6MJRIx6ovV2DdvjX0/DjTH0TtnlhdQUlZx7sDC+bB+ioxh89zRWlnniAAbKPtSOzMvKfvf5my8rTGwKTh8hrs+FGAhoaRhwHes6x9Zi6xrCvYcrZbvm4XXzxqrq7V4xpgZ2eeLKXvnFNG+WXEYCSLoZNUxmprTy7yJW6KkFmkhgsoahu9j8wjfLOVxpHdc6DanuhSUmWKYEyk1uTeg706TrfS5vJifWR6g7FpvdhFyJ8FbqO5age0KpmTd8xkll75XmYePIIcrXG43k9q7NXscWu3maYi3j54y0QaksCLcMn7jTimC92qLl0D8hmIyII4iST4xFsj3CB4N8VVs4qkYBQUMTGweNP/qN/7/BLF2pUJx7kmSruaTnyKqXdgG44WNp+qV0GbuCvOy38yAo5S5ZEspkOhHk16PTcciFlbnDYmkMC0yp2wr58z1kAy+zgU2Bm/FjljjH1LHXXxA8fLPv1cUJJsswy8hKG7pz4Da2/KeQpFC9S8Y8m+uYOAT/g9PAJU+YMwSSbsigQaNQpgRXcwWM1cUvqbe15yKbA8="
    - # ^^ GPG_PASSPHRASE

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn test -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./cd/before-deploy.sh
  - ./cd/deploy.sh