language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "v1ePtByHRqEQWvClfrzcwRLvTk9CFm+Nc3pS9dAso8/s+Xk0hTEisj4Y76/Sp3+vdwbsSPD1vvylpUrdTWzqP+rDO3mlY4jhsLTWGBvw94YDko7Xg2JaQUHVUtI+a8+WY62clYXtH7Cy0F5B1pH7DZK5O99Pqg7RYaiomF9hFIgoaQrJSDiPgfmrGI+A6Cww7JV6/baHqYOvkkPYVt0CiqhIrGRZE4It7fouBekjIIYBp8FsumTxPILoAAFbKfOu1lJxgxfEFJ8gNitroC4J3KwpeUmSYgGDj77WvWOjsca+7FuJbbNMTaxpHr4Qj88i+RLbjJTbQmfw7PA3Yozg/weSUl25msfqKhrS/ipG5LbBw8+i/0t3EefNNXZV9AbdApv203XFWJieFOd7CeNaJZ3HzOhQBpl0tRYEZ6gExz2/7/oz2LErqfxM2Xpuqly40lmC3eEndp92lb8muEmqw7wRAmGa25RO7/8e6QddFM6jJ/csP4xNrAsPU4pJwbf598+xuDChhUZbYPV0rwjPIWpkdFBoxIgEpKHyFuqESmd7p3KJB7mtt+l0u4xmf2HyPNPjC8NavP2W74dPSxnttl3ZnWCx2Jf1a2EUpHutJD0kHrw9d2Qwq7caAl9KiXvQ6gc9ASCoEk2OAMNIN1nRJEZORVccVqOjlDd/kIw2Aa4="
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: "sTeO+UHlQJEH1g/qzxd5EcHyZvbKeDpDVXngUDpWamodXSINwRVFgYoEEhx4jl4Yw/dGab7/UsdOo4YBEZogtvcubAkQ0hsgUgezKCuEVqdvw9uyi2qC94M/LJEszfiz4tbqQnisguK0na2ZFE9IFFvQOpnJkNB4DcN5I0MDbzULt9yJ5LkmeHZttqXkinPMhn1nIGYdiByhcFCY9cwrVWAZ1sPnTLKf+axsdQ55J0ljpG/DJ1h9XSOb4FYDj8gkyEFdbj0ip0nIGp22c+oN3gvKlPdRvyybntXEYnwh631esZBJ0oPIDsre3zkb7+B50niiuGIDVp6MOF++PH5W9ij+d76vMN6KzEIe2zGbacJ3hk1IcES+iswYJP/QgsYTHGSmPJnkUkfcJBQd3gUeG5tl0czQ1yEZ0oQCAC3KgEbIG3oW/Y/yCM37vXrvWPODnz6yZj5nWAiNXktmC3lXr12qs+QJMLR8ecB6PVj9fH0tvD/XVuxBzrUxxIJ2UOUJApEHvthFXesYIDnEfkySuNgZCE4677NXs+yyN8J9bVhW40VfJc682oaYiEzKPdeVQyCL9JuE208Zengs/kf2KaNjMDUGNxii7KEoW2Rge2IA9DyYGYDwGjWuTWGztbcBzGXEPtz6gXvWKRwDRl3Trx6rTrd3sTHBqYbD9jdRORY="
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: "lGIm3b9MJTawQlwHgUmgdzDhYOdwITGPJsXJV6cpBrvEsA/j7DinvdsxiQYbGXygOrDDe+vZoDNE+F6aLpbf0/N3EHr+RYN3jE6fliKqrXeeI+1hWxoV6Q+4O2WahD/quwTQ2asPQe9OM6OUp38GXSE2FSPkY82TLzAutGgqpKS5ShQOsIQlM0rOZEN8OR2Pg5fVv2D1Llcy/0gtJnP7fM4MOXT3GdKO03Vu6tvv60CVOHT555s3SCIQE3NgHzcYHNfceqtlPcE8ymJa5sUmyRPLfPv09owcOCPitGu1Ujn+i0Fj2S7mQF39YQ+oZ/WIT6dx94CredTwC1QfaT6MQU/rn3hubji23KKfTxTQknaGR+DLNlTJZhus7ftPK0HKLY4KsWcRhyVbwbq1g/G+uBLRKA/dLFV8KBe946XQW4fPPX1aqLMV5xWb/thfEsZNNLfhBkrooa1KkPQzzGxTHbrTeZmyugWAaL73OkDQGODpssloVDBIZYId/ZrOjhfvVg8jWht5bpzXIewLFZxPcHYf9n5mfjAdplrnWh9PjbR0fQw8hr3yG97GbNGE8D3YVudf4uBXLKAx8H+1gIq2fgHsLJCvtX/PcToimgiDJRoY4IIB2TquUf7LBTz+mvuWLEzs4gpyHiE56uXAj0dri77iG+H5MooYZxvOYqVK3h0="
    - # ^^ GPG_KEY_NAME
    - secure: "tbqJFuBRvuKZigeGoMjtjxE6BvHIdq330Xfa+Y5nbezfSq26Ibgm++Xr9D96HP3uWiUn5f0Qk1DZBaG715u8Q5pb3IrfrcODwyy9LawDIEMtN+1XipwQAhE/UZXWUlkXQEE4Sb1yXfID4sAnEuDx3QWLPQnpTWKScDn5y+YEz/19SLS1/qhzJ1+G9zripxJiBY1xFItDBFtxMxomcYmKRqiz3osQd8JW4YK+g7fD4AWeB/L19zTYhIWzhZpEq0YrCYaC4u/CXoyIMgueoGe2xiioGS0Wtq2qrx7s3susJa3ihEU7ZB2Wls9zaukVJeACNJnK1iNKEZKeJ5WWRi5hVXkLLcbFjoqU6bgAK45LLaCjz/Oyqs5qrl3b0RPaj+yD8dn2PQMyTfDS7XfirrDG1goeSauydXHIVu38rDu/f1oSm1QUPVA8eafcjJgOYswQmbMeoDue0640Rj/q+KxKzrCqk9xKUjTIMWv7BszdSTqy/11V/rfJuNhAFDn29q73/8NuV1x8+sJ8HkQhCpQopKbmdJvRon0Mp8jXqy7OuN2JnjA1NqKITlWNrwtRWrruIXiFN7lzGxEWBd6M+KR9AqnZToHxON2WQ1qWS84O9Ywm6MDHajvXcY6chbp5WbO0lUsCzAa0NpnbaVbCQcpkeo/lAGueD/FH5Wo/L35lq/c="
    - # ^^ GPG_PASSPHRASE

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn test -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./cd/before-deploy.sh
  - ./cd/deploy.sh